"""initial_schema

Revision ID: 0
Revises: 
Create Date: 2026-01-26 00:36:53.760694

"""
from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financegpt_docs_documents',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financegpt_docs_documents_content_hash'), 'financegpt_docs_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_financegpt_docs_documents_created_at'), 'financegpt_docs_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_financegpt_docs_documents_id'), 'financegpt_docs_documents', ['id'], unique=False)
    op.create_index(op.f('ix_financegpt_docs_documents_source'), 'financegpt_docs_documents', ['source'], unique=True)
    op.create_index(op.f('ix_financegpt_docs_documents_updated_at'), 'financegpt_docs_documents', ['updated_at'], unique=False)
    op.create_table('user',
    sa.Column('pages_limit', sa.Integer(), server_default='500', nullable=False),
    sa.Column('pages_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('searchspaces',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('citations_enabled', sa.Boolean(), nullable=False),
    sa.Column('qna_custom_instructions', sa.Text(), nullable=True),
    sa.Column('agent_llm_id', sa.Integer(), nullable=True),
    sa.Column('document_summary_llm_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchspaces_created_at'), 'searchspaces', ['created_at'], unique=False)
    op.create_index(op.f('ix_searchspaces_id'), 'searchspaces', ['id'], unique=False)
    op.create_index(op.f('ix_searchspaces_name'), 'searchspaces', ['name'], unique=False)
    op.create_table('financegpt_docs_chunks',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['financegpt_docs_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financegpt_docs_chunks_created_at'), 'financegpt_docs_chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_financegpt_docs_chunks_id'), 'financegpt_docs_chunks', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('EXTENSION', 'CRAWLED_URL', 'FILE', 'SLACK_CONNECTOR', 'TEAMS_CONNECTOR', 'NOTION_CONNECTOR', 'YOUTUBE_VIDEO', 'GITHUB_CONNECTOR', 'LINEAR_CONNECTOR', 'DISCORD_CONNECTOR', 'JIRA_CONNECTOR', 'CONFLUENCE_CONNECTOR', 'CLICKUP_CONNECTOR', 'GOOGLE_CALENDAR_CONNECTOR', 'GOOGLE_GMAIL_CONNECTOR', 'GOOGLE_DRIVE_FILE', 'AIRTABLE_CONNECTOR', 'LUMA_CONNECTOR', 'ELASTICSEARCH_CONNECTOR', 'BOOKSTACK_CONNECTOR', 'CIRCLEBACK', 'OBSIDIAN_CONNECTOR', 'NOTE', 'COMPOSIO_CONNECTOR', 'BANK_TRANSACTION', 'CREDIT_CARD_TRANSACTION', 'INVESTMENT_HOLDING', 'INVESTMENT_TRANSACTION', 'ACCOUNT_BALANCE', name='documenttype'), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('unique_identifier_hash', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('blocknote_document', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_needs_reindexing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
    op.create_index(op.f('ix_documents_unique_identifier_hash'), 'documents', ['unique_identifier_hash'], unique=True)
    op.create_index(op.f('ix_documents_updated_at'), 'documents', ['updated_at'], unique=False)
    op.create_table('logs',
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCESS', 'FAILED', name='logstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_source'), 'logs', ['source'], unique=False)
    op.create_index(op.f('ix_logs_status'), 'logs', ['status'], unique=False)
    op.create_table('new_chat_threads',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'SEARCH_SPACE', name='chatvisibility'), server_default='PRIVATE', nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_chat_threads_created_at'), 'new_chat_threads', ['created_at'], unique=False)
    op.create_index(op.f('ix_new_chat_threads_created_by_id'), 'new_chat_threads', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_new_chat_threads_id'), 'new_chat_threads', ['id'], unique=False)
    op.create_index(op.f('ix_new_chat_threads_title'), 'new_chat_threads', ['title'], unique=False)
    op.create_index(op.f('ix_new_chat_threads_updated_at'), 'new_chat_threads', ['updated_at'], unique=False)
    op.create_index(op.f('ix_new_chat_threads_visibility'), 'new_chat_threads', ['visibility'], unique=False)
    op.create_table('new_llm_configs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.Enum('OPENAI', 'ANTHROPIC', 'GOOGLE', 'AZURE_OPENAI', 'BEDROCK', 'VERTEX_AI', 'GROQ', 'COHERE', 'MISTRAL', 'DEEPSEEK', 'XAI', 'OPENROUTER', 'TOGETHER_AI', 'FIREWORKS_AI', 'REPLICATE', 'PERPLEXITY', 'OLLAMA', 'ALIBABA_QWEN', 'MOONSHOT', 'ZHIPU', 'ANYSCALE', 'DEEPINFRA', 'CEREBRAS', 'SAMBANOVA', 'AI21', 'CLOUDFLARE', 'DATABRICKS', 'COMETAPI', 'HUGGINGFACE', 'CUSTOM', name='litellmprovider'), nullable=False),
    sa.Column('custom_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=True),
    sa.Column('litellm_params', sa.JSON(), nullable=True),
    sa.Column('system_instructions', sa.Text(), nullable=False),
    sa.Column('use_default_system_instructions', sa.Boolean(), nullable=False),
    sa.Column('citations_enabled', sa.Boolean(), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_llm_configs_created_at'), 'new_llm_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_new_llm_configs_id'), 'new_llm_configs', ['id'], unique=False)
    op.create_index(op.f('ix_new_llm_configs_name'), 'new_llm_configs', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('podcasts',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('podcast_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_location', sa.Text(), nullable=True),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_created_at'), 'podcasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.create_table('search_source_connectors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('connector_type', sa.Enum('SERPER_API', 'TAVILY_API', 'SEARXNG_API', 'LINKUP_API', 'BAIDU_SEARCH_API', 'SLACK_CONNECTOR', 'TEAMS_CONNECTOR', 'NOTION_CONNECTOR', 'GITHUB_CONNECTOR', 'LINEAR_CONNECTOR', 'DISCORD_CONNECTOR', 'JIRA_CONNECTOR', 'CONFLUENCE_CONNECTOR', 'CLICKUP_CONNECTOR', 'GOOGLE_CALENDAR_CONNECTOR', 'GOOGLE_GMAIL_CONNECTOR', 'GOOGLE_DRIVE_CONNECTOR', 'AIRTABLE_CONNECTOR', 'LUMA_CONNECTOR', 'ELASTICSEARCH_CONNECTOR', 'WEBCRAWLER_CONNECTOR', 'BOOKSTACK_CONNECTOR', 'CIRCLEBACK_CONNECTOR', 'OBSIDIAN_CONNECTOR', 'MCP_CONNECTOR', 'COMPOSIO_CONNECTOR', 'CHASE_BANK', 'CHASE_CREDIT', 'FIDELITY_INVESTMENTS', 'DISCOVER_CREDIT', 'BANK_OF_AMERICA', 'WELLS_FARGO', 'VANGUARD', 'SCHWAB', 'CAPITAL_ONE', 'AMERICAN_EXPRESS', 'GENERIC_BANK_CSV', 'GENERIC_INVESTMENT_CSV', 'OFX_UPLOAD', name='searchsourceconnectortype'), nullable=False),
    sa.Column('is_indexable', sa.Boolean(), nullable=False),
    sa.Column('last_indexed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('periodic_indexing_enabled', sa.Boolean(), nullable=False),
    sa.Column('indexing_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('next_scheduled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_space_id', 'user_id', 'connector_type', 'name', name='uq_searchspace_user_connector_type_name')
    )
    op.create_index(op.f('ix_search_source_connectors_created_at'), 'search_source_connectors', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_source_connectors_id'), 'search_source_connectors', ['id'], unique=False)
    op.create_index(op.f('ix_search_source_connectors_name'), 'search_source_connectors', ['name'], unique=False)
    op.create_table('search_space_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_space_id', 'name', name='uq_searchspace_role_name')
    )
    op.create_index(op.f('ix_search_space_roles_created_at'), 'search_space_roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_space_roles_id'), 'search_space_roles', ['id'], unique=False)
    op.create_index(op.f('ix_search_space_roles_name'), 'search_space_roles', ['name'], unique=False)
    op.create_table('user_memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=True),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('preference', 'fact', 'instruction', 'context', name='memorycategory'), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_created_at'), 'user_memories', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.create_index(op.f('ix_user_memories_search_space_id'), 'user_memories', ['search_space_id'], unique=False)
    op.create_index(op.f('ix_user_memories_updated_at'), 'user_memories', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_table('chat_session_state',
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('ai_responding_to_user_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_responding_to_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['new_chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_state_ai_responding_to_user_id'), 'chat_session_state', ['ai_responding_to_user_id'], unique=False)
    op.create_index(op.f('ix_chat_session_state_id'), 'chat_session_state', ['id'], unique=False)
    op.create_index(op.f('ix_chat_session_state_thread_id'), 'chat_session_state', ['thread_id'], unique=True)
    op.create_table('chunks',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=384), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_created_at'), 'chunks', ['created_at'], unique=False)
    op.create_index(op.f('ix_chunks_id'), 'chunks', ['id'], unique=False)
    op.create_table('new_chat_messages',
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='newchatmessagerole'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['new_chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_chat_messages_author_id'), 'new_chat_messages', ['author_id'], unique=False)
    op.create_index(op.f('ix_new_chat_messages_created_at'), 'new_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_new_chat_messages_id'), 'new_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_new_chat_messages_thread_id'), 'new_chat_messages', ['thread_id'], unique=False)
    op.create_table('search_space_invites',
    sa.Column('invite_code', sa.String(length=64), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['search_space_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_space_invites_created_at'), 'search_space_invites', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_space_invites_id'), 'search_space_invites', ['id'], unique=False)
    op.create_index(op.f('ix_search_space_invites_invite_code'), 'search_space_invites', ['invite_code'], unique=True)
    op.create_table('chat_comments',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['new_chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chat_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['new_chat_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_comments_author_id'), 'chat_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_chat_comments_created_at'), 'chat_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_comments_id'), 'chat_comments', ['id'], unique=False)
    op.create_index(op.f('ix_chat_comments_message_id'), 'chat_comments', ['message_id'], unique=False)
    op.create_index(op.f('ix_chat_comments_parent_id'), 'chat_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_chat_comments_thread_id'), 'chat_comments', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chat_comments_updated_at'), 'chat_comments', ['updated_at'], unique=False)
    op.create_table('search_space_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_space_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('invited_by_invite_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_invite_id'], ['search_space_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['search_space_roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_space_id'], ['searchspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'search_space_id', name='uq_user_searchspace_membership')
    )
    op.create_index(op.f('ix_search_space_memberships_created_at'), 'search_space_memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_space_memberships_id'), 'search_space_memberships', ['id'], unique=False)
    op.create_table('chat_comment_mentions',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['chat_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_comment_mentions_comment_id'), 'chat_comment_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_chat_comment_mentions_created_at'), 'chat_comment_mentions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_comment_mentions_id'), 'chat_comment_mentions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_comment_mentions_mentioned_user_id'), 'chat_comment_mentions', ['mentioned_user_id'], unique=False)
    # ### end Alembic commands ###
    
    # Set REPLICA IDENTITY FULL for Electric SQL sync
    # This is required for Electric to track changes on all columns
    op.execute("""
        DO $$
        DECLARE
            r RECORD;
        BEGIN
            FOR r IN 
                SELECT tablename 
                FROM pg_tables 
                WHERE schemaname = 'public' 
                AND tablename NOT IN ('alembic_version', 'spatial_ref_sys')
            LOOP
                EXECUTE 'ALTER TABLE public.' || quote_ident(r.tablename) || ' REPLICA IDENTITY FULL';
            END LOOP;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_comment_mentions_mentioned_user_id'), table_name='chat_comment_mentions')
    op.drop_index(op.f('ix_chat_comment_mentions_id'), table_name='chat_comment_mentions')
    op.drop_index(op.f('ix_chat_comment_mentions_created_at'), table_name='chat_comment_mentions')
    op.drop_index(op.f('ix_chat_comment_mentions_comment_id'), table_name='chat_comment_mentions')
    op.drop_table('chat_comment_mentions')
    op.drop_index(op.f('ix_search_space_memberships_id'), table_name='search_space_memberships')
    op.drop_index(op.f('ix_search_space_memberships_created_at'), table_name='search_space_memberships')
    op.drop_table('search_space_memberships')
    op.drop_index(op.f('ix_chat_comments_updated_at'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_thread_id'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_parent_id'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_message_id'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_id'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_created_at'), table_name='chat_comments')
    op.drop_index(op.f('ix_chat_comments_author_id'), table_name='chat_comments')
    op.drop_table('chat_comments')
    op.drop_index(op.f('ix_search_space_invites_invite_code'), table_name='search_space_invites')
    op.drop_index(op.f('ix_search_space_invites_id'), table_name='search_space_invites')
    op.drop_index(op.f('ix_search_space_invites_created_at'), table_name='search_space_invites')
    op.drop_table('search_space_invites')
    op.drop_index(op.f('ix_new_chat_messages_thread_id'), table_name='new_chat_messages')
    op.drop_index(op.f('ix_new_chat_messages_id'), table_name='new_chat_messages')
    op.drop_index(op.f('ix_new_chat_messages_created_at'), table_name='new_chat_messages')
    op.drop_index(op.f('ix_new_chat_messages_author_id'), table_name='new_chat_messages')
    op.drop_table('new_chat_messages')
    op.drop_index(op.f('ix_chunks_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_created_at'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_chat_session_state_thread_id'), table_name='chat_session_state')
    op.drop_index(op.f('ix_chat_session_state_id'), table_name='chat_session_state')
    op.drop_index(op.f('ix_chat_session_state_ai_responding_to_user_id'), table_name='chat_session_state')
    op.drop_table('chat_session_state')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_updated_at'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_search_space_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_created_at'), table_name='user_memories')
    op.drop_table('user_memories')
    op.drop_index(op.f('ix_search_space_roles_name'), table_name='search_space_roles')
    op.drop_index(op.f('ix_search_space_roles_id'), table_name='search_space_roles')
    op.drop_index(op.f('ix_search_space_roles_created_at'), table_name='search_space_roles')
    op.drop_table('search_space_roles')
    op.drop_index(op.f('ix_search_source_connectors_name'), table_name='search_source_connectors')
    op.drop_index(op.f('ix_search_source_connectors_id'), table_name='search_source_connectors')
    op.drop_index(op.f('ix_search_source_connectors_created_at'), table_name='search_source_connectors')
    op.drop_table('search_source_connectors')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_created_at'), table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_new_llm_configs_name'), table_name='new_llm_configs')
    op.drop_index(op.f('ix_new_llm_configs_id'), table_name='new_llm_configs')
    op.drop_index(op.f('ix_new_llm_configs_created_at'), table_name='new_llm_configs')
    op.drop_table('new_llm_configs')
    op.drop_index(op.f('ix_new_chat_threads_visibility'), table_name='new_chat_threads')
    op.drop_index(op.f('ix_new_chat_threads_updated_at'), table_name='new_chat_threads')
    op.drop_index(op.f('ix_new_chat_threads_title'), table_name='new_chat_threads')
    op.drop_index(op.f('ix_new_chat_threads_id'), table_name='new_chat_threads')
    op.drop_index(op.f('ix_new_chat_threads_created_by_id'), table_name='new_chat_threads')
    op.drop_index(op.f('ix_new_chat_threads_created_at'), table_name='new_chat_threads')
    op.drop_table('new_chat_threads')
    op.drop_index(op.f('ix_logs_status'), table_name='logs')
    op.drop_index(op.f('ix_logs_source'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_documents_updated_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_unique_identifier_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_title'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_financegpt_docs_chunks_id'), table_name='financegpt_docs_chunks')
    op.drop_index(op.f('ix_financegpt_docs_chunks_created_at'), table_name='financegpt_docs_chunks')
    op.drop_table('financegpt_docs_chunks')
    op.drop_index(op.f('ix_searchspaces_name'), table_name='searchspaces')
    op.drop_index(op.f('ix_searchspaces_id'), table_name='searchspaces')
    op.drop_index(op.f('ix_searchspaces_created_at'), table_name='searchspaces')
    op.drop_table('searchspaces')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_financegpt_docs_documents_updated_at'), table_name='financegpt_docs_documents')
    op.drop_index(op.f('ix_financegpt_docs_documents_source'), table_name='financegpt_docs_documents')
    op.drop_index(op.f('ix_financegpt_docs_documents_id'), table_name='financegpt_docs_documents')
    op.drop_index(op.f('ix_financegpt_docs_documents_created_at'), table_name='financegpt_docs_documents')
    op.drop_index(op.f('ix_financegpt_docs_documents_content_hash'), table_name='financegpt_docs_documents')
    op.drop_table('financegpt_docs_documents')
    # ### end Alembic commands ###
